Syslog			yes
#Logwhy                  yes
#LogResults              yes
#SyslogSuccess           yes
MilterDebug             4
#Diagnostics             yes
#DiagnosticDirectory     /etc/opendkim/diagnostics

UMask			002

#Domain			atmaprema.yoga, cminfosec.com
#KeyFile		/etc/dkimkeys/dkim.key
#Selector		2007

Canonicalization	relaxed/simple
Mode			sv
SubDomains		no
AutoRestart             yes
AutoRestartRate         10/1M
Background              yes
DNSTimeout              5
SignatureAlgorithm      rsa-sha256

Socket			local:/var/spool/postfix/opendkim/opendkim.sock
PidFile                 /var/run/opendkim/opendkim.pid
OversignHeaders		From
UserID                  opendkim

SigningTable            refile:/etc/opendkim/SigningTable
KeyTable                /etc/opendkim/KeyTable

ExternalIgnoreList      refile:/etc/opendkim/TrustedHosts
InternalHosts           refile:/etc/opendkim/TrustedHosts

