[Interface]
PrivateKey = aAw01PLuxlW7UOwuNxJIWIIys7Sbv7rKz7EVEi1bBHA=
Address = 10.51.51.7/24
ListenPort = 59701
PostUp = resolvectl dns %i 10.51.50.1; resolvectl domain %i ~nelson.fam

[Peer]
PublicKey = JAW0zAVvrl8zvI429cJJOv0bQNAnnFRjREKWVwYmvmY=
PresharedKey = 5ZBa56WS3lqN3OE9B8u9sXxkLHmo6tpo+rm5Defb0oY=
Endpoint = paddle.duckdns.org:51820
AllowedIPs = 10.51.50.0/24, 10.51.60.0/24
PersistentKeepalive = 25
